applications:
  - name: example-app   # name of the application in Argo CD
    namespace: default  # Kubernetes namespace
    project: default    # name of the Argo CD project
    source:             # source of the application code
      # repoURL: https://github.com/YOUR_USERNAME/example-repo.git
      repoURL: ${github_repo_url}  # Git repository URL where the Helm chart or Kubernetes manifests are stored
      path: charts/django-app      # path inside the repo to the required chart or YAML files
      targetRevision: lesson-8-9   # Git branch or tag to deploy from (e.g., main)
      helm:
        valueFiles:                # list of YAML files with settings passed to the Helm chart
          - values.yaml
    destination:                               # where to deploy the application
      server: https://kubernetes.default.svc   # address of the Kubernetes API server; for internal clusters, use https://kubernetes.default.svc
      namespace: default                       # Kubernetes namespace for this specific application
    syncPolicy:            # sync policy
      automated:           # enables automatic application of changes
        prune: true        # delete resources no longer defined in Git
        selfHeal: true     # automatically fix drift from Git state if something is changed manually in the cluster

repositories:
  - name: example-app           # name of the repository for internal reference
    # url: https://github.com/YOUR_USERNAME/example-repo.git
    url: ${github_repo_url}     # full URL of the Git repository
    username: ${github_user}    # credentials for accessing the private repository
    password: ${github_pat}

repoConfig:
  insecure: "true"    # allow repository access without SSL certificate verification; not recommended for production
  enableLfs: "true"   # enable Git LFS (Large File Storage) support if the repository contains large files