apiVersion: v2
name: django-app
version: 0.1.0
description: A Helm chart for Kubernetes
type: application
appVersion: 1.16.0

dependencies:
  - name: postgresql
    version: 16.7.15
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled