image:
  repository: 349298600530.dkr.ecr.ap-southeast-2.amazonaws.com/ecr-dev
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: true

env:
  DJANGO_SETTINGS_MODULE: 'myproject.settings'
  DATABASE_URL: 'postgres://user:password@host:port/dbname'
